services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # ローカル開発環境のプロファイルを使用
      - SPRING_PROFILES_ACTIVE=local
      # 本番環境にデプロイする場合は以下に変更:
      # - SPRING_PROFILES_ACTIVE=production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fx-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=fxtrade
      - POSTGRES_USER=fxuser
      - POSTGRES_PASSWORD=fxpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fxuser -d fxtrade"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fx-network

volumes:
  postgres_data:

networks:
  fx-network:
    driver: bridge